cc_binary(
    name = "example_dataframe",
    srcs = ["dataframe.cpp"],
    deps = [
        "//:data_crunching",
    ]
)

cc_binary(
    name = "example_namedtuple",
    srcs = ["namedtuple.cpp"],
    deps = [
        "//:data_crunching",
    ]
)